# Generated by Django 5.2.8 on 2025-12-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_gif_url'),
        ('posts', '0002_post_edited_by_post_last_edited'),
    ]

    operations = [
    ]
