# Generated by Django 5.2.8 on 2025-12-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_20251207_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
