# Generated by Django 5.2.8 on 2025-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_warning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warning',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='warning',
            name='nivel',
            field=models.CharField(choices=[('leve', 'Leve'), ('media', 'Media'), ('grave', 'Grave')], default='leve', max_length=10),
            preserve_default=False,
        ),
    ]
