# Generated by Django 5.2.8 on 2025-12-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_message_warning_mensaje_warning_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warning',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
