# Generated by Django 5.2.8 on 2025-12-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_warning_active_warning_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='visto_admin',
            field=models.BooleanField(default=False),
        ),
    ]
