# Generated by Django 5.2.8 on 2025-12-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='image',
        ),
    ]
