# Generated by Django 5.2.8 on 2025-12-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
